name: sonin_ia
description: Sonin.IA — Assistente pessoal inteligente para a Dona Sônia
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # VOZ
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  just_audio: ^0.9.36

  # BANCO DE DADOS
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2

  # INTERNET
  http: ^1.2.1

  # NOTIFICAÇÕES
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

  # ABRIR OUTROS APPS
  url_launcher: ^6.2.6

  # IMAGENS
  cached_network_image: ^3.3.1

  # DEVOCIONAL — pacotes novos
  intl: ^0.19.0          # formatação de datas
  audioplayers: ^6.0.0   # tocar música gospel

  # UTILITÁRIOS
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/verses/versiculos.json

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Italic.ttf
          style: italic
